Update Cargo.toml debug value from integer to bool
Encounter following error on MacOS:
```shell
make app
cargo build --release
error: failed to parse manifest at `/Users/work/rust_workspace/alacritty/Cargo.toml`

Caused by:
  expected a value of type `bool`, but found a value of type `integer` for the key `profile.release.debug`
make: *** [alacritty] Error 101
```